package relational

// generated by ChatGPT

import (
	"database/sql"
	"fmt"
	_ "github.com/lib/pq"
)

type DataSourceConnectionData struct {
	Host     string
	Port     string
	Username string
	Password string
}

func GetDBConnection(ds DataSourceConnectionData) (*sql.DB, error) {
	connStr := fmt.Sprintf("host=%s port=%s user=%s password=%s sslmode=disable",
		ds.Host, ds.Port, ds.Username, ds.Password)

	db, err := sql.Open("postgres", connStr)
	if err != nil {
		return nil, err
	}

	err = db.Ping()
	if err != nil {
		return nil, err
	}

	return db, nil
}
